### ISSUE TITLE
添加各大厂商的内网节点

### ISSUE THREAD

**Issue by Lemonawa** [SuperManito/LinuxMirrors#11]
比如 https://mirrors.tencentyun.com （外网打不开）

**Comment by SuperManito** [comment]
> 比如 https://mirrors.tencentyun.com （外网打不开）

这个我知道的，但是一般出厂镜像内置的软件源就是内网线路，我觉得意义不大就没搞

**Comment by Lemonawa** [comment]
> > 比如 https://mirrors.tencentyun.com （外网打不开）
> 
> 这个我知道的，但是一般出厂镜像内置的软件源就是内网线路，我觉得意义不大就没搞

不过还是会有手残、中病毒之类的情况

**Comment by SuperManito** [comment]
已添加阿里云、腾讯云、华为云的开源镜像站内网地址
