### ISSUE TITLE
希望增加无人值守命令行方式

### ISSUE THREAD

**Issue by hackroad** [SuperManito/LinuxMirrors#12]
1：目前我是自己根据需求加入了镜像出现问题无法使用时继续流程及无人值守的形式
2：加入海外镜像可用节点，海外服务器回阿里还是太慢了

**Comment by SuperManito** [comment]
> 1：目前我是自己根据需求加入了镜像出现问题无法使用时继续流程及无人值守的形式 2：加入海外镜像可用节点，海外服务器回阿里还是太慢了

1. 不太明白你说的无人值守是什么效果，本身从脚本开始执行到结束1分钟就差不多完成了，是应用到集群服务器吗？

2. 你指的是 Linux 换源还是 Docker 换源，如果是 LInux 那你自己改下脚本中的地址就好了，逻辑都是没问题直接改下面的链接即可定制你自己的脚本

**Comment by hackroad** [comment]
> > 1：目前我是自己根据需求加入了镜像出现问题无法使用时继续流程及无人值守的形式 2：加入海外镜像可用节点，海外服务器回阿里还是太慢了
> 
> 1. 不太明白你说的无人值守是什么效果，本身从脚本开始执行到结束1分钟就差不多完成了，是应用到集群服务器吗？
> 2. 你指的是 Linux 换源还是 Docker 换源，如果是 LInux 那你自己改下脚本中的地址就好了，逻辑都是没问题直接改下面的链接即可定制你自己的脚本

1：就是脚本那可以配置交互方式进行更换，还是不用交互直接前台或者后台执行。
2：海外镜像节点就是RedHat 系的发行版和及其部分衍生版本的海外源，目前脚本内当前使用的开源镜像站都是国内的，希望加入海外镜像站

**Comment by SuperManito** [comment]
> > > 1：目前我是自己根据需求加入了镜像出现问题无法使用时继续流程及无人值守的形式 2：加入海外镜像可用节点，海外服务器回阿里还是太慢了
> > 
> > 
> > 
> > 1. 不太明白你说的无人值守是什么效果，本身从脚本开始执行到结束1分钟就差不多完成了，是应用到集群服务器吗？
> > 2. 你指的是 Linux 换源还是 Docker 换源，如果是 LInux 那你自己改下脚本中的地址就好了，逻辑都是没问题直接改下面的链接即可定制你自己的脚本
> 
> 1：就是脚本那可以配置交互方式进行更换，还是不用交互直接前台或者后台执行。 2：海外镜像节点就是RedHat 系的发行版和及其部分衍生版本的海外源，目前脚本内当前使用的开源镜像站都是国内的，希望加入海外镜像站

不了解海外镜像站，你可以介绍几个，可以搞官方源

**Comment by SNAKEXGC** [comment]
我也希望能够新增一个海外源，可以是官方源，我记得麻省理工好像也有源，希望能够加进去，因为海外的服务器，有时候用dd脚本后会下载国内已经修改过源的镜像，而海外的服务器请求这些源速度很慢

**Comment by tension** [comment]
> > 1：目前我是自己根据需求加入了镜像出现问题无法使用时继续流程及无人值守的形式 2：加入海外镜像可用节点，海外服务器回阿里还是太慢了
> 
> 1. 不太明白你说的无人值守是什么效果，本身从脚本开始执行到结束1分钟就差不多完成了，是应用到集群服务器吗？
> 2. 你指的是 Linux 换源还是 Docker 换源，如果是 LInux 那你自己改下脚本中的地址就好了，逻辑都是没问题直接改下面的链接即可定制你自己的脚本



其实就是快捷安装，比如 安装命令后带  163 自动安装成 163 的源 不需要选择和输入 就自动安装成功的

**Comment by Goojoe** [comment]
我猜是命令行方式不是交互确认的,比如 xxx.sh 163 y y y

**Comment by SuperManito** [comment]
> 我猜是命令行方式不是交互确认的,比如 xxx.sh 163 y y y

这个我有空了会写，就是脚本传参，很简单
