### ISSUE TITLE
epel源可能都失效了

### ISSUE THREAD

**Issue by o02** [SuperManito/LinuxMirrors#16]
failure: repodata/repomd.xml from epel: [Errno 256] No more mirrors to try.
http://mirrors.cloud.tencent.com/epel/8.5-1.2111.el8/Everything/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

[ERROR] 软件源同步失败

**Comment by SuperManito** [comment]
修了 重新换源试试呢

**Comment by o02** [comment]
已经正常，大佬牛B【破音】
