### ISSUE TITLE
腾讯云轻量切换源失败，所有源都报错

### ISSUE THREAD

**Issue by chaos-zhu** [SuperManito/LinuxMirrors#17]
## 1. 处理器架构

- [x] `x86_64` `x86_32`
- [ ] `arm64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 2. 使用环境

- [ ] `Debian`
- [ ] `Ubuntu`
- [ ] `Kali Linux`
- [ ] `Red Hat Enterprise Linux`
- [x] `CentOS`
- [ ] `Fedora`

## 3. 使用环境版本

A：Linux VM-8-2-centos 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### (1) 具体问题
A：
腾讯云轻量切换源失败，所有源都报下面错误

### (2) 详细的系统日志

A：
Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/CentOS-Epel.repo; Configuration: OptionBinding with id "failovermethod" does not exist
Repository extras is listed more than once in the configuration
Repository epel is listed more than once in the configuration
CentOS-8.5.2111 - Base - mirrors.aliyun.com                                           1.1 MB/s | 4.6 MB     00:04    
CentOS-8.5.2111 - Extras - mirrors.aliyun.com                                         134 kB/s |  10 kB     00:00    
CentOS-8.5.2111 - AppStream - mirrors.aliyun.com                                      1.1 MB/s | 8.4 MB     00:07    
EPEL for redhat/centos 8.5.2111 - x86_64                                              4.7 kB/s | 244  B     00:00    
Errors during downloading metadata for repository 'epel':
  - Status code: 404 for http://mirrors.tencentyun.com/epel/8.5.2111/Everything/x86_64/repodata/repomd.xml (IP: 169.254.0.3)
Error: Failed to download metadata for repo 'epel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by SuperManito** [comment]
已更换腾讯云镜像站新的公网地址

旧的公网地址路径可能已在近期停止解析，官方文档自更换以来一直能用，所以一直没有注意到这个问题

https://github.com/tencentyun/qcloud-documents/commit/c849e51148a79d9e65ec73ff4ca51a97e5fa955e
