### ISSUE TITLE
ubuntu 22.10  error

### ISSUE THREAD

**Issue by gitlsl** [SuperManito/LinuxMirrors#18]
## 1. 处理器架构

- [x ] `x86_64` `x86_32`
- [ ] `arm64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 2. 使用环境

- [ ] `Debian`
- [ x] `Ubuntu`
- [ ] `Kali Linux`
- [ ] `Red Hat Enterprise Linux`
- [ ] `CentOS`
- [ ] `Fedora`

## 3. 使用环境版本

A：
Linux DESKTOP-LV6G37D 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
### (1) 具体问题
A：
sudo bash <(curl -sSL https://gitee.com/SuperManito/LinuxMirrors/raw/main/ChangeMirrors.sh)
[sudo] password for lsl:
bash: /dev/fd/63: No such file or directory
### (2) 详细的系统日志

A：
bash: /dev/fd/63: No such file or directory

**Comment by SuperManito** [comment]
https://github.com/SuperManito/LinuxMirrors/blob/d3fb873abb28cea09e2cc940c6d9c74740a84647/README.md?plain=1#L79
