### ISSUE TITLE
希望增加对镜像站的测速功能

### ISSUE THREAD

**Issue by songkaicc** [SuperManito/LinuxMirrors#21]
首先这是一个非常棒的脚本，感谢您的贡献与分享。
在使用过程中，发现一些问题，由于每个人所在的区域不同，网络不同，每个镜像站的加速效果不同，如果能加上测速功能，则对选择最快的镜像站有很好的帮助，目前使用脚本都需要反复测试出最快的站点才行。

**Comment by XCyber** [comment]
脚本很不错，要是有测速功能就更好了。

**Comment by ruchid123123** [comment]
很好用，多谢了

**Comment by hestiacn** [comment]
> 首先这是一个非常棒的脚本，感谢您的贡献与分享。 在使用过程中，发现一些问题，由于每个人所在的区域不同，网络不同，每个镜像站的加速效果不同，如果能加上测速功能，则对选择最快的镜像站有很好的帮助，目前使用脚本都需要反复测试出最快的站点才行。

站点已经推荐使用中科大的镜像源了。中科大的源速度都不慢。

**Comment by SuperManito** [comment]
> 确实应该加个测速功能 类似这种就更好了![Screenshot_2024-12-26-19-14-56-396_tv.danmaku.bili.jpg](https://private-user-images.githubusercontent.com/84552324/398715853-73332f98-084f-4443-acb7-44efc4d92e16.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTQ2MjcsIm5iZiI6MTczNTI5NDMyNywicGF0aCI6Ii84NDU1MjMyNC8zOTg3MTU4NTMtNzMzMzJmOTgtMDg0Zi00NDQzLWFjYjctNDRlZmM0ZDkyZTE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDEwMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjliNGQyMzE1NGFmNDhlMmFjZWRhNjI5NGJiNWExZjNiMDUxMzMwMmEyNjc0NjlkMzdmNGM4MmE4NzBjNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qHImWtwfoQaDz8IWE-Cjr2sMRmDINnNzWrdFGPCNTBQ)

**Comment by SuperManito** [comment]
> > 确实应该加个测速功能 类似这种就更好了![Screenshot_2024-12-26-19-14-56-396_tv.danmaku.bili.jpg](https://private-user-images.githubusercontent.com/84552324/398715853-73332f98-084f-4443-acb7-44efc4d92e16.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTQ2MjcsIm5iZiI6MTczNTI5NDMyNywicGF0aCI6Ii84NDU1MjMyNC8zOTg3MTU4NTMtNzMzMzJmOTgtMDg0Zi00NDQzLWFjYjctNDRlZmM0ZDkyZTE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDEwMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMjliNGQyMzE1NGFmNDhlMmFjZWRhNjI5NGJiNWExZjNiMDUxMzMwMmEyNjc0NjlkMzdmNGM4MmE4NzBjNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qHImWtwfoQaDz8IWE-Cjr2sMRmDINnNzWrdFGPCNTBQ)
> 
> 我已经研究过了，首先这个延迟代表不了什么，另外想要测算下载速度大概率需要通过一些高级语言实现，而使用其它高级语言就需要安装其环境，这违背脚本的初衷。

另外关于 Docker Hub 镜像加速有太多个人域名代理了，本项目一般不会去收集这种类型的镜像地址。
