### ISSUE TITLE
操作系统是rocky9 更换国内源失败

### ISSUE THREAD

**Issue by moguangjian** [SuperManito/LinuxMirrors#26]
## 1. 操作系统

- [ ] `Debian`
- [ ] `Ubuntu`
- [ ] `Kali Linux`
- [ ] `Red Hat Enterprise Linux`
- [ ] `CentOS`
- [ ] `CentOS Stream`
- [ ] `Fedora`
- [x] `Rocky Linux`
- [ ] `openEuler`
- [ ] `openSUSE`

## 2. 处理器架构

- [ ] `x86_64` `x86_32`
- [ ] `arm64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 3. 系统详细信息

```

```

## 4. 环境信息

```

```

### (1) 具体问题
A：

### (2) 详细的系统日志

```

```

**Comment by SuperManito** [comment]
> ## 1. 操作系统
> * [ ]  `Debian`
> * [ ]  `Ubuntu`
> * [ ]  `Kali Linux`
> * [ ]  `Red Hat Enterprise Linux`
> * [ ]  `CentOS`
> * [ ]  `CentOS Stream`
> * [ ]  `Fedora`
> * [x]  `Rocky Linux`
> * [ ]  `openEuler`
> * [ ]  `openSUSE`
> 
> ## 2. 处理器架构
> * [ ]  `x86_64` `x86_32`
> * [ ]  `arm64` `arm/v8` `arm/v7` `arm/v6`
> * [ ]  `ppc64le` `s390x`
> * [ ]  `Other`
> 
> ## 3. 系统详细信息
> ```
> 
> ```
> 
> ## 4. 环境信息
> ```
> 
> ```
> 
> ## 5. 详细叙述你的问题
> ### (1) 具体问题
> A：
> 
> ### (2) 详细的系统日志
> ```
> 
> ```

日志都不发怎么帮你解决
