### ISSUE TITLE
希望能加入对Raspberry Pi OS的支持

### ISSUE THREAD

**Issue by cj233cj** [SuperManito/LinuxMirrors#28]
最近重装树莓派系统发现提示系统版本不支持

**Comment by SuperManito** [comment]
> 最近重装树莓派系统发现提示系统版本不支持

用的人太少了，而且我这里不具备测试环境

**Comment by SuperManito** [comment]
如果你想适配此系统那么需要你提供一些信息并协助我进行测试

- `/etc/apt/sources.list.d/raspi.list` 文件的原始内容
- `/etc/os-release` 和 `/etc/debian_version` 的文件内容
- 执行 `lsb_release -a` 命令的结果
- 执行 `uname -a` 命令的结果

此外据我查阅资料所知，Raspbian 的 arm64 版本和 armhf 版本有些许不同，在系统判断上可能会出现问题，所以你可能需要分别提供不同架构的上述信息

**Comment by cj233cj** [comment]
抱歉我的树莓派目前装的Ubuntu系统，暂时没有精力协助测试
