### ISSUE TITLE
希望添加pip, npm, docker等常见国内源

### ISSUE THREAD

**Issue by everdom** [SuperManito/LinuxMirrors#29]
系统太多了，配环境真烦，本来自己想写一个脚本来着，结果找到了这里，看来没必要重复造轮子了，感谢作者开源！如果国内源能一锅端那将更好，哈哈

**Comment by SuperManito** [comment]
> 系统太多了，配环境真烦，本来自己想写一个脚本来着，结果找到了这里，看来没必要重复造轮子了，感谢作者开源！如果国内源能一锅端那将更好，哈哈

pip、npm这种一行命令就解决换源了，没必要些什么脚本，pip的源还挺多的npm很少，没必要写啥脚本，docker不是已经有了么。。。

**Comment by everdom** [comment]
不就图个方便吗，那一行命令也可以换ubuntu的源，还要脚本干啥，是docker仓库的国内源，不是docker

**Comment by everdom** [comment]
都有脚本了，还要输命令，还是不够自动吧。。。算了，还是自己写脚本方便

**Comment by everdom** [comment]
哦，看到了，docker是一个单独的脚本是吧。不过我觉得单独换一个linux源意义不大，如果能一个脚本把各种软件源一次性配好，那才足够的方便，不然你用了脚本还要输命令换源那还不如一开始都都用命令算了，毕竟换个linux源也一行命令足以

**Comment by SuperManito** [comment]
> 哦，看到了，docker是一个单独的脚本是吧。不过我觉得单独换一个linux源意义不大，如果能一个脚本把各种软件源一次性配好，那才足够的方便，不然你用了脚本还要输命令换源那还不如一开始都都用命令算了，毕竟换个linux源也一行命令足以

你是咋看的文档？
