### ISSUE TITLE
腾讯轻量云香港30m安装docker失败

### ISSUE THREAD

**Issue by sd462355991111** [SuperManito/LinuxMirrors#3]
1. 使用平台架构

- [x ] `amd64` `x86_64` `x86_32`
- [ ] `aarch64` `arm64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 2. 使用环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Kali

## 3. 使用环境版本

A：Linux VM-0-13-centos 4.11.8-1.el7.elrepo.x86_64 #1 SMP Thu Jun 29 10:01:10 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

### (1) 具体问题
A：国外的，就是那个腾讯轻量云香港30m，跟新加坡30m  2台服务器都是安装docker失败。
用这个命令查看docker-compose --version   可以显示版本
用这个命令查看docker --version  显示-bash: docker: 未找到命令

### (2) 详细的系统日志

A：

**Comment by sd462355991111** [comment]
![image](https://user-images.githubusercontent.com/78030698/122389600-ad5b6900-cfa3-11eb-8040-7610192f49b5.png)

**Comment by SuperManito** [comment]
发日志
