### ISSUE TITLE
一键换回官方源

### ISSUE THREAD

**Issue by o-liverkk** [SuperManito/LinuxMirrors#30]
感谢开发，脚本很好用。

希望能增加换回官方源的功能。

**Comment by SuperManito** [comment]
> 感谢开发，脚本很好用。
> 
> 希望能增加换回官方源的功能。

还原备份即可 https://linuxmirrors.cn/use/help/#%E8%BF%98%E5%8E%9F%E5%B7%B2%E5%A4%87%E4%BB%BD%E7%9A%84%E8%BD%AF%E4%BB%B6%E6%BA%90

**Comment by o-liverkk** [comment]
你说的对，但是如果备份丢失了，或者服务商本来设置的就不是官方源，这该怎么办呢。

所以还是希望能有换到官方源的功能。
