### ISSUE TITLE
增加换至官方源

### ISSUE THREAD

**Issue by o-liverkk** [SuperManito/LinuxMirrors#31]
#30 

你说的对，但是如果备份丢失了，或者服务商本来设置的就不是官方源，这该怎么办呢。

所以还是希望能有换到官方源的功能。

**Comment by SuperManito** [comment]
> #30
> 
> 你说的对，但是如果备份丢失了，或者服务商本来设置的就不是官方源，这该怎么办呢。
> 
> 所以还是希望能有换到官方源的功能。

基本上没啥人用官方源吧，这个项目用户的目的是很明确的，并且你可以命令选项指定软件源来换回官方源 https://linuxmirrors.cn/use/command-options

**Comment by SuperManito** [comment]
> #30
> 
> 你说的对，但是如果备份丢失了，或者服务商本来设置的就不是官方源，这该怎么办呢。
> 
> 所以还是希望能有换到官方源的功能。

已增加相关命令选项 https://linuxmirrors.cn/use/command-options/#%E6%81%A2%E5%A4%8D%E5%AE%98%E6%96%B9%E6%BA%90
