### ISSUE TITLE
可以加入ProxmoxVE的支持么

### ISSUE THREAD

**Issue by laaArmy** [SuperManito/LinuxMirrors#32]

**Comment by SuperManito** [comment]
我没用过PVE，它不是一个跟 Vmware EXSi 类似的虚拟机系统吗，需要换源？

**Comment by SuperManito** [comment]
我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库

**Comment by OldLi1997** [comment]
> 我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库

企业源和ct源需要单独加入

**Comment by SuperManito** [comment]
> > 我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库
> 
> 企业源和ct源需要单独加入

首先换源得有源可换，你知道它在哪些镜像站有镜像吗？

**Comment by OldLi1997** [comment]
> > > 我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库
> > 
> > 企业源和ct源需要单独加入
> 
> 首先换源得有源可换，你知道它在哪些镜像站有镜像吗？

清华和中科大都有

**Comment by OldLi1997** [comment]
> > > 我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库
> > 
> > 企业源和ct源需要单独加入
> 
> 首先换源得有源可换，你知道它在哪些镜像站有镜像吗？

pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list
deb https://mirrors.tuna.tsinghua.edu.cn/proxmox/debian/pve bookworm pve-no-subscription

cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back 
sed -i 's|http://download.proxmox.com|https://mirrors.tuna.tsinghua.edu.cn/proxmox|g' /usr/share/perl5/PVE/APLInfo.pm


pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list
deb https://mirrors.ustc.edu.cn/proxmox/debian bookworm pve-no-subscription

cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back
sed -i 's|http://download.proxmox.com|https://mirrors.ustc.edu.cn/proxmox|g' /usr/share/perl5/PVE/APLInfo.pm




PVE 8 之后默认安装 ceph 仓库源文件 /etc/apt/sources.list.d/ceph.list，可以使用如下命令更换源：

if [ -f /etc/apt/sources.list.d/ceph.list ]; then CEPH_CODENAME=`ceph -v | grep ceph | awk '{print $(NF-1)}'`; source /etc/os-release; echo "deb https://mirrors.ustc.edu.cn/proxmox/debian/ceph-$CEPH_CODENAME $VERSION_CODENAME no-subscription" > /etc/apt/sources.list.d/ceph.list; fi

**Comment by SuperManito** [comment]
> > > > 我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库
> > > 
> > > 
> > > 企业源和ct源需要单独加入
> > 
> > 
> > 首先换源得有源可换，你知道它在哪些镜像站有镜像吗？
> 
> 清华大学 pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list deb https://mirrors.tuna.tsinghua.edu.cn/proxmox/debian/pve bookworm pve-no-subscription
> 
> cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back sed -i 's|[http://download.proxmox.com|https://mirrors.tuna.tsinghua.edu.cn/proxmox|g](http://download.proxmox.com%7Chttps://mirrors.tuna.tsinghua.edu.cn/proxmox%7Cg)' /usr/share/perl5/PVE/APLInfo.pm
> 
> 中国科学技术大学 pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list deb https://mirrors.ustc.edu.cn/proxmox/debian bookworm pve-no-subscription
> 
> cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back sed -i 's|[http://download.proxmox.com|https://mirrors.ustc.edu.cn/proxmox|g](http://download.proxmox.com%7Chttps://mirrors.ustc.edu.cn/proxmox%7Cg)' /usr/share/perl5/PVE/APLInfo.pm
> 
> ceph源
> 
> PVE 8 之后默认安装 ceph 仓库源文件 /etc/apt/sources.list.d/ceph.list，可以使用如下命令更换源：
> 
> if [ -f /etc/apt/sources.list.d/ceph.list ]; then CEPH_CODENAME=`ceph -v | grep ceph | awk '{print $(NF-1)}'`; source /etc/os-release; echo "deb https://mirrors.ustc.edu.cn/proxmox/debian/ceph-$CEPH_CODENAME $VERSION_CODENAME no-subscription" > /etc/apt/sources.list.d/ceph.list; fi



> > > > 我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库
> > > 
> > > 
> > > 企业源和ct源需要单独加入
> > 
> > 
> > 首先换源得有源可换，你知道它在哪些镜像站有镜像吗？
> 
> 清华大学 pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list deb https://mirrors.tuna.tsinghua.edu.cn/proxmox/debian/pve bookworm pve-no-subscription
> 
> cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back sed -i 's|[http://download.proxmox.com|https://mirrors.tuna.tsinghua.edu.cn/proxmox|g](http://download.proxmox.com%7Chttps://mirrors.tuna.tsinghua.edu.cn/proxmox%7Cg)' /usr/share/perl5/PVE/APLInfo.pm
> 
> 中国科学技术大学 pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list deb https://mirrors.ustc.edu.cn/proxmox/debian bookworm pve-no-subscription
> 
> cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back sed -i 's|[http://download.proxmox.com|https://mirrors.ustc.edu.cn/proxmox|g](http://download.proxmox.com%7Chttps://mirrors.ustc.edu.cn/proxmox%7Cg)' /usr/share/perl5/PVE/APLInfo.pm
> 
> ceph源
> 
> PVE 8 之后默认安装 ceph 仓库源文件 /etc/apt/sources.list.d/ceph.list，可以使用如下命令更换源：
> 
> if [ -f /etc/apt/sources.list.d/ceph.list ]; then CEPH_CODENAME=`ceph -v | grep ceph | awk '{print $(NF-1)}'`; source /etc/os-release; echo "deb https://mirrors.ustc.edu.cn/proxmox/debian/ceph-$CEPH_CODENAME $VERSION_CODENAME no-subscription" > /etc/apt/sources.list.d/ceph.list; fi

脚本仅更换 `/etc/apt/sources.list` 文件内的系统软件源，不涉及 `/etc/apt/sources.list.d` 目录下第三方软件源

**Comment by OldLi1997** [comment]
> > > > > 我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库
> > > > 
> > > > 
> > > > 企业源和ct源需要单独加入
> > > 
> > > 
> > > 首先换源得有源可换，你知道它在哪些镜像站有镜像吗？
> > 
> > 清华大学 pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list deb https://mirrors.tuna.tsinghua.edu.cn/proxmox/debian/pve bookworm pve-no-subscription
> > 
> > cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back sed -i 's|[http://download.proxmox.com|https://mirrors.tuna.tsinghua.edu.cn/proxmox|g](http://download.proxmox.com%7Chttps://mirrors.tuna.tsinghua.edu.cn/proxmox%7Cg)' /usr/share/perl5/PVE/APLInfo.pm
> > 
> > 中国科学技术大学 pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list deb https://mirrors.ustc.edu.cn/proxmox/debian bookworm pve-no-subscription
> > 
> > cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back sed -i 's|[http://download.proxmox.com|https://mirrors.ustc.edu.cn/proxmox|g](http://download.proxmox.com%7Chttps://mirrors.ustc.edu.cn/proxmox%7Cg)' /usr/share/perl5/PVE/APLInfo.pm
> > 
> > ceph源
> > 
> > PVE 8 之后默认安装 ceph 仓库源文件 /etc/apt/sources.list.d/ceph.list，可以使用如下命令更换源：
> > 
> > if [ -f /etc/apt/sources.list.d/ceph.list ]; then CEPH_CODENAME=`ceph -v | grep ceph | awk '{print $(NF-1)}'`; source /etc/os-release; echo "deb https://mirrors.ustc.edu.cn/proxmox/debian/ceph-$CEPH_CODENAME $VERSION_CODENAME no-subscription" > /etc/apt/sources.list.d/ceph.list; fi
> 
> 
> 
> > > > > 我查了一下，它是Debian的衍生版，你要是用apt装东西的话搞一份debian的源进去就行了，外边貌似没有它的镜像仓库
> > > > 
> > > > 
> > > > 企业源和ct源需要单独加入
> > > 
> > > 
> > > 首先换源得有源可换，你知道它在哪些镜像站有镜像吗？
> > 
> > 清华大学 pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list deb https://mirrors.tuna.tsinghua.edu.cn/proxmox/debian/pve bookworm pve-no-subscription
> > 
> > cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back sed -i 's|[http://download.proxmox.com|https://mirrors.tuna.tsinghua.edu.cn/proxmox|g](http://download.proxmox.com%7Chttps://mirrors.tuna.tsinghua.edu.cn/proxmox%7Cg)' /usr/share/perl5/PVE/APLInfo.pm
> > 
> > 中国科学技术大学 pve 镜像默认的 pve 软件源配置文件是 /etc/apt/sources.list.d/pve-enterprise.list deb https://mirrors.ustc.edu.cn/proxmox/debian bookworm pve-no-subscription
> > 
> > cp /usr/share/perl5/PVE/APLInfo.pm /usr/share/perl5/PVE/APLInfo.pm_back sed -i 's|[http://download.proxmox.com|https://mirrors.ustc.edu.cn/proxmox|g](http://download.proxmox.com%7Chttps://mirrors.ustc.edu.cn/proxmox%7Cg)' /usr/share/perl5/PVE/APLInfo.pm
> > 
> > ceph源
> > 
> > PVE 8 之后默认安装 ceph 仓库源文件 /etc/apt/sources.list.d/ceph.list，可以使用如下命令更换源：
> > 
> > if [ -f /etc/apt/sources.list.d/ceph.list ]; then CEPH_CODENAME=`ceph -v | grep ceph | awk '{print $(NF-1)}'`; source /etc/os-release; echo "deb https://mirrors.ustc.edu.cn/proxmox/debian/ceph-$CEPH_CODENAME $VERSION_CODENAME no-subscription" > /etc/apt/sources.list.d/ceph.list; fi
> 
> 脚本仅更换 `/etc/apt/sources.list` 文件内的系统软件源，不涉及 `/etc/apt/sources.list.d` 目录下第三方软件源

好的，麻烦了
