### ISSUE TITLE
PVE安装docker

### ISSUE THREAD

**Issue by allonmymind** [SuperManito/LinuxMirrors#34]
PVE7.0或者8.0使用容器安装脚本安装docker后，finalshell会加载不出sftp文件，能解决吗？

**Comment by SuperManito** [comment]
> PVE7.0或者8.0使用容器安装脚本安装docker后，finalshell会加载不出sftp文件，能解决吗？

首先脚本仅支持原版debian系统，我并没有在PVE系统上进行过测试，其次安装脚本并不会更改相关系统设置，你的问题与脚本本身没有任何关联，如果你坚持你的观点请附上截图证据
