### ISSUE TITLE
希望添加Ali龙蜥OS的支持

### ISSUE THREAD

**Issue by bzw1204** [SuperManito/LinuxMirrors#35]

**Comment by SuperManito** [comment]
无法支持，因为这系统除了自家阿里云压根就没有镜像站同步它，而且这系统每个版本的镜像源配置都不一样

**Comment by bzw1204** [comment]
> 无法支持，因为这系统除了自家阿里云压根就没有镜像站同步它，而且这系统每个版本的镜像源配置都不一样

懂了，还说能用一下呢
