### ISSUE TITLE
我有3台运行脚本后 中挖矿木马

### ISSUE THREAD

**Issue by syscc** [SuperManito/LinuxMirrors#37]
## 1. 操作系统

- [x] `Debian`
- [x] `Ubuntu`
- [ ] `Kali Linux`
- [ ] `Red Hat Enterprise Linux`
- [ ] `CentOS / CentOS Stream`
- [ ] `Fedora`
- [ ] `AlmaLinux`
- [ ] `Rocky Linux`
- [ ] `OpenCloudOS`
- [ ] `openEuler`
- [ ] `openSUSE`

## 2. 处理器架构

- [x] `x86_64` `x86_32`
- [x] `arm64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 3. 系统详细信息

```

```

## 4. 环境信息

```

```

### (1) 具体问题
A：

### (2) 详细的系统日志

```

```

**Comment by syscc** [comment]
kdevtmpfsi

**Comment by SuperManito** [comment]
你自己的问题，ssh密码爆破攻击很常见建议用密钥登录并关闭密码登录，项目脚本与你的问题无关

**Comment by syscc** [comment]
我之前一直没问题，用你这个脚本安装docker后 昨晚开始就出现cpu百分百使用率，也没安装docker redis
