### ISSUE TITLE
希望可以支持麒麟及统信的支持

### ISSUE THREAD

**Issue by majornian** [SuperManito/LinuxMirrors#38]
希望可以适配支持麒麟V10 及统信UOS20 的支持。

**Comment by SuperManito** [comment]
商业系统一搬没有软件源可以换，但是统信UOS可以换自家Deepin的源，回头我适配一下，麒麟应该没有源可换

**Comment by SuperManito** [comment]
简单看了一下，适配的意义不大，商业软件换源本身意义就不大并且没什么源可以换就别提有多少镜像站可用了

这个 `统信UOS Server` 有多个基于不同Linux派系的版本（龙蜥、openEuler等）。。。给人感觉上就是加了个自家的桌面技术

这个龙蜥之所以没有适配一方面是因为它每个版本的软件源配置不一样很麻烦，最主要的还是它就没几个公共镜像站可用，我只查到阿里云镜像站有，使用人数较低于同行的 OpenCloudOS 和 openEuler，商用版本出了一大堆
