### ISSUE TITLE
【功能请求】：添加armbian源

### ISSUE THREAD

**Issue by LSP0123** [SuperManito/LinuxMirrors#40]
armbian官方列出源：`https://github.com/armbian/mirror/blob/master/README.md`

cn，apt源：
http://mirror.iscas.ac.cn/armbian/
http://mirror.sjtu.edu.cn/armbian/
http://mirror.ossplanet.net/armbian/apt/
http://mirrors.aliyun.com/armbian/
http://mirrors.bfsu.edu.cn/armbian/
http://mirrors.nju.edu.cn/armbian/
http://mirrors.shanghaitech.edu.cn/armbian/
http://mirrors.shanghaitech.edu.cn/armbian/
http://mirrors.tuna.tsinghua.edu.cn/armbian/
http://mirrors.ustc.edu.cn/armbian/

**Comment by SuperManito** [comment]
请分别提供

> armbian官方列出源：`https://github.com/armbian/mirror/blob/master/README.md`
> 
> cn，apt源： http://mirror.iscas.ac.cn/armbian/ http://mirror.sjtu.edu.cn/armbian/ http://mirror.ossplanet.net/armbian/apt/ http://mirrors.aliyun.com/armbian/ http://mirrors.bfsu.edu.cn/armbian/ http://mirrors.nju.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.tuna.tsinghua.edu.cn/armbian/ http://mirrors.ustc.edu.cn/armbian/

请分别提供 `/etc/os-release` 和 `/etc/debian_version` 的文件内容

**Comment by LSP0123** [comment]
> 请分别提供
> 
> > armbian官方列出源：`https://github.com/armbian/mirror/blob/master/README.md`
> > cn，apt源： http://mirror.iscas.ac.cn/armbian/ http://mirror.sjtu.edu.cn/armbian/ http://mirror.ossplanet.net/armbian/apt/ http://mirrors.aliyun.com/armbian/ http://mirrors.bfsu.edu.cn/armbian/ http://mirrors.nju.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.tuna.tsinghua.edu.cn/armbian/ http://mirrors.ustc.edu.cn/armbian/
> 
> 请分别提供以下信息：
> 
> * `/etc/os-release` 和 `/etc/debian_version` 的文件内容
> * 执行 `lsb_release -is` 和 `lsb_release -cs` 命令的结果


```
n1:~:% cat /etc/os-release     
PRETTY_NAME="Armbian-unofficial 24.2.0-trunk jammy"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
PRIVACY_POLICY_URL="https://www.armbian.com"
UBUNTU_CODENAME=jammy
ARMBIAN_PRETTY_NAME="Armbian-unofficial 24.2.0-trunk jammy"
n1:~:% cat /etc/debian_version
bookworm/sid
n1:~:% lsb_release -is
Ubuntu
n1:~:% lsb_release -cs
jammy

```
以上为armbian的ubuntu-jammy版内容，当前使用镜像来源[ophub](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2024.01)的[Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2024.01/Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img.gz)


armbian-official当前分为debian（bookworm、bullseye）版和ubuntu（jammy）版，（bullseye快不支持了），其中ubuntu版会同时启用armbian源和ubuntu-ports源，以下为修改为ali-mirros的sourcelist文件内容
```
n1:~:% cat /etc/apt/sources.list
deb https://mirrors.aliyun.com/ubuntu-ports/ jammy main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy main restricted universe multiverse

deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-security main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-security main restricted universe multiverse

deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-updates main restricted universe multiverse

deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
# deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-backports main restricted universe multiverse

n1:~:% cat /etc/apt/sources.list.d/armbian.list 
deb [signed-by=/usr/share/keyrings/armbian.gpg] https://mirrors.aliyun.com/armbian/ jammy main jammy-utils jammy-desktop

```

**Comment by SuperManito** [comment]
> > 请分别提供
> > > armbian官方列出源：`https://github.com/armbian/mirror/blob/master/README.md`
> > > cn，apt源： http://mirror.iscas.ac.cn/armbian/ http://mirror.sjtu.edu.cn/armbian/ http://mirror.ossplanet.net/armbian/apt/ http://mirrors.aliyun.com/armbian/ http://mirrors.bfsu.edu.cn/armbian/ http://mirrors.nju.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.tuna.tsinghua.edu.cn/armbian/ http://mirrors.ustc.edu.cn/armbian/
> > 
> > 
> > 请分别提供以下信息：
> > 
> > * `/etc/os-release` 和 `/etc/debian_version` 的文件内容
> > * 执行 `lsb_release -is` 和 `lsb_release -cs` 命令的结果
> 
> ```
> n1:~:% cat /etc/os-release     
> PRETTY_NAME="Armbian-unofficial 24.2.0-trunk jammy"
> NAME="Ubuntu"
> VERSION_ID="22.04"
> VERSION="22.04.3 LTS (Jammy Jellyfish)"
> VERSION_CODENAME=jammy
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.armbian.com"
> SUPPORT_URL="https://forum.armbian.com"
> BUG_REPORT_URL="https://www.armbian.com/bugs"
> PRIVACY_POLICY_URL="https://www.armbian.com"
> UBUNTU_CODENAME=jammy
> ARMBIAN_PRETTY_NAME="Armbian-unofficial 24.2.0-trunk jammy"
> n1:~:% cat /etc/debian_version
> bookworm/sid
> n1:~:% lsb_release -is
> Ubuntu
> n1:~:% lsb_release -cs
> jammy
> ```
> 
> 以上为armbian的ubuntu-jammy版内容，当前使用镜像来源[ophub](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2024.01)的[Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2024.01/Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img.gz)
> 
> armbian-official当前分为debian（bookworm、bullseye）版和ubuntu（jammy）版，（bullseye快不支持了），其中ubuntu版会同时启用armbian源和ubuntu-ports源，以下为修改为ali-mirros的sourcelist文件内容
> 
> ```
> n1:~:% cat /etc/apt/sources.list
> deb https://mirrors.aliyun.com/ubuntu-ports/ jammy main restricted universe multiverse
> # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy main restricted universe multiverse
> 
> deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-security main restricted universe multiverse
> # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-security main restricted universe multiverse
> 
> deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
> # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
> 
> deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
> # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
> 
> n1:~:% cat /etc/apt/sources.list.d/armbian.list 
> deb [signed-by=/usr/share/keyrings/armbian.gpg] https://mirrors.aliyun.com/armbian/ jammy main jammy-utils jammy-desktop
> ```

请继续分别提供以下信息：

  - 请提供 `/etc/armbian-release` 文件的内容
  - 请提供命令 `ls /etc/apt` 的执行结果
  - 请提供对于当前16个默认镜像站的支持情况汇总

**Comment by LSP0123** [comment]
```
n1:~:% cat /etc/armbian-release 
# PLEASE DO NOT EDIT THIS FILE
BOARD=odroidn2
BOARD_NAME="Aml-S905d"
BOARDFAMILY=meson-g12b
BUILD_REPOSITORY_URL=https://github.com/armbian/build.git
BUILD_REPOSITORY_COMMIT=6cd3981
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=rebuild
BOARD_TYPE=diy
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image
FORCE_BOOTSCRIPT_UPDATE=no
VENDOR="Armbian-unofficial"
VENDORDOCS="https://docs.armbian.com/"
VENDORURL="https://duckduckgo.com/"
VENDORSUPPORT="https://community.armbian.com/"
VENDORBUGS="https://armbian.atlassian.net/"
FORCE_BOOTSCRIPT_UPDATE="no"
BOOTSCRIPT_DST="boot.cmd"
VERSION=24.2.0
REVISION=24.2.0-trunk
BRANCH=current

n1:~:% ls /etc/apt
apt.conf.d  auth.conf.d  keyrings  preferences.d  sources.list  sources.list.d  trusted.gpg.d

```
@SuperManito 
您说的默认镜像站支持情况汇总是？
这几个都支持ubuntu（jammy）和debian（bookworm），具体上游站没有一个个检查，但是停止支持的版本代号也都在，能够看到还有deb包

**Comment by SuperManito** [comment]
> ```
> n1:~:% cat /etc/armbian-release 
> # PLEASE DO NOT EDIT THIS FILE
> BOARD=odroidn2
> BOARD_NAME="Aml-S905d"
> BOARDFAMILY=meson-g12b
> BUILD_REPOSITORY_URL=https://github.com/armbian/build.git
> BUILD_REPOSITORY_COMMIT=6cd3981
> LINUXFAMILY=meson64
> ARCH=arm64
> IMAGE_TYPE=rebuild
> BOARD_TYPE=diy
> INITRD_ARCH=arm64
> KERNEL_IMAGE_TYPE=Image
> FORCE_BOOTSCRIPT_UPDATE=no
> VENDOR="Armbian-unofficial"
> VENDORDOCS="https://docs.armbian.com/"
> VENDORURL="https://duckduckgo.com/"
> VENDORSUPPORT="https://community.armbian.com/"
> VENDORBUGS="https://armbian.atlassian.net/"
> FORCE_BOOTSCRIPT_UPDATE="no"
> BOOTSCRIPT_DST="boot.cmd"
> VERSION=24.2.0
> REVISION=24.2.0-trunk
> BRANCH=current
> 
> n1:~:% ls /etc/apt
> apt.conf.d  auth.conf.d  keyrings  preferences.d  sources.list  sources.list.d  trusted.gpg.d
> ```
> 
> @SuperManito 您说的默认镜像站支持情况汇总是？ 这几个都支持ubuntu（jammy）和debian（bookworm），具体上游站没有一个个检查，但是停止支持的版本代号也都在，能够看到还有deb包

支持情况汇总指的是我要给文档软件源表格那里做统计，另外Armbian自家软件源的么是不是配置在了 `/etc/apt/sources.list.d` 目录下的某个文件里边？

**Comment by LSP0123** [comment]
> > 请分别提供
> > > armbian官方列出源：`https://github.com/armbian/mirror/blob/master/README.md`
> > > cn，apt源： http://mirror.iscas.ac.cn/armbian/ http://mirror.sjtu.edu.cn/armbian/ http://mirror.ossplanet.net/armbian/apt/ http://mirrors.aliyun.com/armbian/ http://mirrors.bfsu.edu.cn/armbian/ http://mirrors.nju.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.tuna.tsinghua.edu.cn/armbian/ http://mirrors.ustc.edu.cn/armbian/
> > 
> > 
> > 请分别提供以下信息：
> > 
> > * `/etc/os-release` 和 `/etc/debian_version` 的文件内容
> > * 执行 `lsb_release -is` 和 `lsb_release -cs` 命令的结果
> 
> ```
> n1:~:% cat /etc/os-release     
> PRETTY_NAME="Armbian-unofficial 24.2.0-trunk jammy"
> NAME="Ubuntu"
> VERSION_ID="22.04"
> VERSION="22.04.3 LTS (Jammy Jellyfish)"
> VERSION_CODENAME=jammy
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.armbian.com"
> SUPPORT_URL="https://forum.armbian.com"
> BUG_REPORT_URL="https://www.armbian.com/bugs"
> PRIVACY_POLICY_URL="https://www.armbian.com"
> UBUNTU_CODENAME=jammy
> ARMBIAN_PRETTY_NAME="Armbian-unofficial 24.2.0-trunk jammy"
> n1:~:% cat /etc/debian_version
> bookworm/sid
> n1:~:% lsb_release -is
> Ubuntu
> n1:~:% lsb_release -cs
> jammy
> ```
> 
> 以上为armbian的ubuntu-jammy版内容，当前使用镜像来源[ophub](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2024.01)的[Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2024.01/Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img.gz)
> 
> armbian-official当前分为debian（bookworm、bullseye）版和ubuntu（jammy）版，（bullseye快不支持了），其中ubuntu版会同时启用armbian源和ubuntu-ports源，以下为修改为ali-mirros的sourcelist文件内容
> 
> ```
> n1:~:% cat /etc/apt/sources.list
> deb https://mirrors.aliyun.com/ubuntu-ports/ jammy main restricted universe multiverse
> # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy main restricted universe multiverse
> 
> deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-security main restricted universe multiverse
> # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-security main restricted universe multiverse
> 
> deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
> # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
> 
> deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
> # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
> 
> n1:~:% cat /etc/apt/sources.list.d/armbian.list 
> deb [signed-by=/usr/share/keyrings/armbian.gpg] https://mirrors.aliyun.com/armbian/ jammy main jammy-utils jammy-desktop
> ```


```
n1:~:% cat /etc/apt/sources.list.d/armbian.list 
deb [signed-by=/usr/share/keyrings/armbian.gpg] https://mirrors.aliyun.com/armbian/ jammy main jammy-utils jammy-desktop
```
之前已经给你列出来了，两个cat的文件就是全部的source.list内容

“支持情况汇总指的是我要给文档软件源表格那里做统计”我还是没有看懂你这句话的意思。
你是想说codename还是什么？
我最开始列出的镜像站都是armbian官方的readme里的

**Comment by SuperManito** [comment]
> > > 请分别提供
> > > > armbian官方列出源：`https://github.com/armbian/mirror/blob/master/README.md`
> > > > cn，apt源： http://mirror.iscas.ac.cn/armbian/ http://mirror.sjtu.edu.cn/armbian/ http://mirror.ossplanet.net/armbian/apt/ http://mirrors.aliyun.com/armbian/ http://mirrors.bfsu.edu.cn/armbian/ http://mirrors.nju.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.shanghaitech.edu.cn/armbian/ http://mirrors.tuna.tsinghua.edu.cn/armbian/ http://mirrors.ustc.edu.cn/armbian/
> > > 
> > > 
> > > 请分别提供以下信息：
> > > 
> > > * `/etc/os-release` 和 `/etc/debian_version` 的文件内容
> > > * 执行 `lsb_release -is` 和 `lsb_release -cs` 命令的结果
> > 
> > 
> > ```
> > n1:~:% cat /etc/os-release     
> > PRETTY_NAME="Armbian-unofficial 24.2.0-trunk jammy"
> > NAME="Ubuntu"
> > VERSION_ID="22.04"
> > VERSION="22.04.3 LTS (Jammy Jellyfish)"
> > VERSION_CODENAME=jammy
> > ID=ubuntu
> > ID_LIKE=debian
> > HOME_URL="https://www.armbian.com"
> > SUPPORT_URL="https://forum.armbian.com"
> > BUG_REPORT_URL="https://www.armbian.com/bugs"
> > PRIVACY_POLICY_URL="https://www.armbian.com"
> > UBUNTU_CODENAME=jammy
> > ARMBIAN_PRETTY_NAME="Armbian-unofficial 24.2.0-trunk jammy"
> > n1:~:% cat /etc/debian_version
> > bookworm/sid
> > n1:~:% lsb_release -is
> > Ubuntu
> > n1:~:% lsb_release -cs
> > jammy
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 以上为armbian的ubuntu-jammy版内容，当前使用镜像来源[ophub](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2024.01)的[Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2024.01/Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img.gz)
> > armbian-official当前分为debian（bookworm、bullseye）版和ubuntu（jammy）版，（bullseye快不支持了），其中ubuntu版会同时启用armbian源和ubuntu-ports源，以下为修改为ali-mirros的sourcelist文件内容
> > ```
> > n1:~:% cat /etc/apt/sources.list
> > deb https://mirrors.aliyun.com/ubuntu-ports/ jammy main restricted universe multiverse
> > # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy main restricted universe multiverse
> > 
> > deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-security main restricted universe multiverse
> > # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-security main restricted universe multiverse
> > 
> > deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
> > # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-updates main restricted universe multiverse
> > 
> > deb https://mirrors.aliyun.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
> > # deb-src https://mirrors.aliyun.com/ubuntu-ports/ jammy-backports main restricted universe multiverse
> > 
> > n1:~:% cat /etc/apt/sources.list.d/armbian.list 
> > deb [signed-by=/usr/share/keyrings/armbian.gpg] https://mirrors.aliyun.com/armbian/ jammy main jammy-utils jammy-desktop
> > ```
> 
> ```
> n1:~:% cat /etc/apt/sources.list.d/armbian.list 
> deb [signed-by=/usr/share/keyrings/armbian.gpg] https://mirrors.aliyun.com/armbian/ jammy main jammy-utils jammy-desktop
> ```
> 
> 之前已经给你列出来了，两个cat的文件就是全部的source.list内容
> 
> “支持情况汇总指的是我要给文档软件源表格那里做统计”我还是没有看懂你这句话的意思。 你是想说codename还是什么？ 我最开始列出的镜像站都是armbian官方的readme里的

按照现有脚本逻辑，Armbian系统执行后应该会正常配置Debian或Ubuntu软件源的，只是没有配置Armbian的专用源

**Comment by LSP0123** [comment]
armbian的专用在/etc/apt/sources.list.d/armbian.list 里，而且是同时使用debian和ubuntu的codename，具体看系统一开始是编译为哪个版本的

**Comment by SuperManito** [comment]
> armbian的专用在/etc/apt/sources.list.d/armbian.list 里，而且是同时使用debian和ubuntu的codename，具体看系统一开始是编译为哪个版本的

docker一键安装脚本在armbian应该能正常使用吧

**Comment by LSP0123** [comment]
暂时还没试，ophub的armbian自带了安装docker的脚本，这几天我试下

**Comment by SuperManito** [comment]
> 暂时还没试，ophub的armbian自带了安装docker的脚本，这几天我试下

已提交适配，请尽快协助本项目完成测试，另外再测一下Docker安装脚本

**Comment by LSP0123** [comment]
> > 暂时还没试，ophub的armbian自带了安装docker的脚本，这几天我试下
> 
> 已提交适配，请尽快协助本项目完成测试，另外再测一下Docker安装脚本


bookworm测试情况：
平台：树莓派3b
OS：Armbian_23.11.2_Rpi4b_bookworm_current_6.1.68_minimal.img    （armbian-official）
sha：eca9b2bd6dad67bcb727f139b2df13a05e59c68111b755160d6e688c0242b65d



系统源测试结果：
```
pi@rpi3b:~$ cat /etc/apt/sources.list
## 默认禁用源码镜像以提高速度，如需启用请自行取消注释
deb http://mirrors.aliyun.com/debian bookworm main contrib non-free non-free-firmware
# deb-src http://mirrors.aliyun.com/debian bookworm main contrib non-free non-free-firmware
deb http://mirrors.aliyun.com/debian bookworm-updates main contrib non-free non-free-firmware
# deb-src http://mirrors.aliyun.com/debian bookworm-updates main contrib non-free non-free-firmware
deb http://mirrors.aliyun.com/debian bookworm-backports main contrib non-free non-free-firmware
# deb-src http://mirrors.aliyun.com/debian bookworm-backports main contrib non-free non-free-firmware
deb http://mirrors.aliyun.com/debian-security bookworm-security main contrib non-free non-free-firmware
# deb-src http://mirrors.aliyun.com/debian-security bookworm-security main contrib non-free non-free-firmware
deb http://mirrors.aliyun.com/armbian bookworm main bookworm-utils bookworm-desktop
```

```
pi@rpi3b:~$ cat /etc/apt/sources.list.d/armbian.list
```

```
pi@rpi3b:~$ cat /etc/apt/sources.list.d/armbian.list.bak 
deb [signed-by=/usr/share/keyrings/armbian.gpg] http://apt.armbian.com bookworm main bookworm-utils bookworm-desktop
```


armbian源写入位置错误（实际写入：`/etc/apt/sources.list`；预期写入：`/etc/apt/sources.list.d/armbian.list`），armbian源公钥配置丢失，debian bookworm源修改成功




docker安装脚本测试情况：
1.使用错误源无法安装（缺少密钥导致armbian源无法更新，从而脚本中断）
2.手动配置好系统源之后：docker源配置成功，安装正常进行
```
pi@rpi3b:~$ cat /etc/apt/sources.list.d/docker.list 
deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.aliyun.com/docker-ce/linux/debian bookworm stable
```




jammy版晚点测试，要上班

**Comment by LSP0123** [comment]
jammy版情况同bookworm

**Comment by SuperManito** [comment]
已修

**Comment by LSP0123** [comment]
@SuperManito  jammy测试ok bookworm我就不测了，应该是没啥问题，感谢您的工作。
