### ISSUE TITLE
希望能标出 哪些支持ipv6

### ISSUE THREAD

**Issue by tanpengsccd** [SuperManito/LinuxMirrors#43]
### 请在下方描述您的功能请求或建议

感谢开发者无偿整理这些源.

**Comment by SuperManito** [comment]
https://linuxmirrors.cn/mirrors/#%E4%B8%AD%E5%9B%BD%E5%A4%A7%E9%99%86

你是怎么看的文档

**Comment by tanpengsccd** [comment]
是我没说清楚，我是希望 脚本能显示IPv6支持与否.
