### ISSUE TITLE
[BUG] 一键执行命令后，不断循环输出"请输入数字序号以选择你想要的源"

### ISSUE THREAD

**Issue by DDDDD12138** [SuperManito/LinuxMirrors#48]
### 操作系统

Deepin

### 处理器架构

x86_64 / x86_32

### 系统详细信息

PRETTY_NAME="Deepin 23"
NAME="Deepin"
VERSION_ID="23"
VERSION="23"
ID=Deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="https://bbs.deepin.org"
VERSION_CODENAME=beige

### 环境信息

Linux deepin 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux

### 问题
一键执行命令后，不断循环输出"请输入数字序号以选择你想要的源"

### 视频

https://github.com/SuperManito/LinuxMirrors/assets/43703884/9d56cbb2-1bf3-40e8-a692-e334b1a699a1

### 详细的执行日志

sudo bash < <(curl -sSL https://linuxmirrors.cn/main.sh)

**Comment by SuperManito** [comment]
不要用sudo执行，`sudo -i` 切换到root

**Comment by SuperManito** [comment]
> ### 操作系统
> Deepin
> 
> ### 处理器架构
> x86_64 / x86_32
> 
> ### 系统详细信息
> PRETTY_NAME="Deepin 23" NAME="Deepin" VERSION_ID="23" VERSION="23" ID=Deepin HOME_URL="https://www.deepin.org/" BUG_REPORT_URL="https://bbs.deepin.org" VERSION_CODENAME=beige
> 
> ### 环境信息
> Linux deepin 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux
> 
> ### 描述您的问题
> ### 问题
> 一键执行命令后，不断循环输出"请输入数字序号以选择你想要的源"
> 
> ### 视频
>  _org.deepin.browser_20240707131207.mp4 
> ### 详细的执行日志
> sudo bash < <(curl -sSL https://linuxmirrors.cn/main.sh)


不要用sudo执行，`sudo -i` 切换到root

**Comment by DDDDD12138** [comment]
> > ### 操作系统
> > Deepin
> > ### 处理器架构
> > x86_64 / x86_32
> > ### 系统详细信息
> > PRETTY_NAME="Deepin 23" NAME="Deepin" VERSION_ID="23" VERSION="23" ID=Deepin HOME_URL="https://www.deepin.org/" BUG_REPORT_URL="https://bbs.deepin.org" VERSION_CODENAME=beige
> > ### 环境信息
> > Linux deepin 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux
> > ### 描述您的问题
> > ### 问题
> > 一键执行命令后，不断循环输出"请输入数字序号以选择你想要的源"
> > ### 视频
> > _org.deepin.browser_20240707131207.mp4
> > ### 详细的执行日志
> > sudo bash < <(curl -sSL https://linuxmirrors.cn/main.sh)
> 
> 不要用sudo执行，`sudo -i` 切换到root

还是一样的噢

![image](https://github.com/SuperManito/LinuxMirrors/assets/43703884/9d8a837b-5f59-4076-9230-a81f80074548)

**Comment by SuperManito** [comment]
> > > ### 操作系统
> > > Deepin
> > > ### 处理器架构
> > > x86_64 / x86_32
> > > ### 系统详细信息
> > > PRETTY_NAME="Deepin 23" NAME="Deepin" VERSION_ID="23" VERSION="23" ID=Deepin HOME_URL="https://www.deepin.org/" BUG_REPORT_URL="https://bbs.deepin.org" VERSION_CODENAME=beige
> > > ### 环境信息
> > > Linux deepin 6.6.25-amd64-desktop-hwe #23.01.00.25 SMP PREEMPT_DYNAMIC Wed Apr 10 21:20:25 CST 2024 x86_64 GNU/Linux
> > > ### 描述您的问题
> > > ### 问题
> > > 一键执行命令后，不断循环输出"请输入数字序号以选择你想要的源"
> > > ### 视频
> > > _org.deepin.browser_20240707131207.mp4
> > > ### 详细的执行日志
> > > sudo bash < <(curl -sSL https://linuxmirrors.cn/main.sh)
> > 
> > 
> > 不要用sudo执行，`sudo -i` 切换到root
> 
> 还是一样的噢
> 
> ![image](https://private-user-images.githubusercontent.com/43703884/346350960-9d8a837b-5f59-4076-9230-a81f80074548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjE0OTEsIm5iZiI6MTcyMDQyMTE5MSwicGF0aCI6Ii80MzcwMzg4NC8zNDYzNTA5NjAtOWQ4YTgzN2ItNWY1OS00MDc2LTkyMzAtYTgxZjgwMDc0NTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzIzODIxOWI3ODFhOTNhMjEyYTI0ZmZmZTdiOWVjN2JhZDI3OWIwNjQzMTRkMTljM2NjYmI1YTcwNzA3YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._JkZSiekHtCDzUDJRWvt5k2NGVF3SWOGk7qSK8SJC8g)

你系统终端问题吧 换ssh试试
