### ISSUE TITLE
部分源已经不维护

### ISSUE THREAD

**Issue by w4iting4** [SuperManito/LinuxMirrors#49]
### 请在下方描述您的功能请求或建议

CentOS 7 已于 2024 年 6 月 30 日结束维护，我们强烈建议立即迁移到其他解决方案。如有需要继续使用 CentOS，请查阅 [CentOS Vault](https://mirrors.tuna.tsinghua.edu.cn/help/centos-vault/) 帮助。
CentOS Stream 相关镜像见 [CentOS Stream](https://mirrors.tuna.tsinghua.edu.cn/help/centos-stream/) 帮助。
尝试了中科院、阿里、腾讯、清华等多个源，均失去了维护，后续是否会为centos增加其他源呢？

**Comment by SuperManito** [comment]
> ### 请在下方描述您的功能请求或建议
> CentOS 7 已于 2024 年 6 月 30 日结束维护，我们强烈建议立即迁移到其他解决方案。如有需要继续使用 CentOS，请查阅 [CentOS Vault](https://mirrors.tuna.tsinghua.edu.cn/help/centos-vault/) 帮助。 CentOS Stream 相关镜像见 [CentOS Stream](https://mirrors.tuna.tsinghua.edu.cn/help/centos-stream/) 帮助。 尝试了中科院、阿里、腾讯、清华等多个源，均失去了维护，后续是否会为centos增加其他源呢？

已提交更新
