### ISSUE TITLE
能否一次性添加多个镜像站的

### ISSUE THREAD

**Issue by Wang-Mer** [SuperManito/LinuxMirrors#50]
如题

_No response_

**Comment by SuperManito** [comment]
> 如题
> 
> _No response_

有什么意义？

**Comment by Wang-Mer** [comment]
我在的网络有点不好，不稳定，比如说我现在使用阿里可以使用，过下次安装软件时就不能使用，换一个就又好了

**Comment by Wang-Mer** [comment]
我也找过能不能解决，没找到问题在哪里

**Comment by SuperManito** [comment]
中科大、字节跳动(火山引擎)、腾讯云 从里面挑个
