### ISSUE TITLE
生成软件源缓存异常，可以的话，请考虑docker 等其他外部源跳过的问题

### ISSUE THREAD

**Issue by CxistHans** [SuperManito/LinuxMirrors#56]
### 操作系统

CentOS / CentOS Stream

### 处理器架构

x86_64 / x86_32

### 系统详细信息

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### 环境信息

Linux localhost.localdomain 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 描述您的问题

生成软件源缓存 异常：
![image](https://github.com/user-attachments/assets/0eb659be-74d7-4a3a-8eaa-52d00c5f35dd)
请考虑docker 等其他外部源的问题

### 详细的执行日志

无

**Comment by SuperManito** [comment]
> ### 操作系统
> CentOS / CentOS Stream
> 
> ### 处理器架构
> x86_64 / x86_32
> 
> ### 系统详细信息
> NAME="CentOS Linux" VERSION="7 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"
> 
> ### 环境信息
> Linux localhost.localdomain 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> 
> ### 描述您的问题
> 生成软件源缓存 异常： ![image](https://private-user-images.githubusercontent.com/52312956/360285709-0eb659be-74d7-4a3a-8eaa-52d00c5f35dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTkyNjYsIm5iZiI6MTcyNDMxODk2NiwicGF0aCI6Ii81MjMxMjk1Ni8zNjAyODU3MDktMGViNjU5YmUtNzRkNy00YTNhLThlYWEtNTJkMDBjNWYzNWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NTY5YWM5ZmI1YTNjZmVhNTdhOWI5NjJmOWY1MWEzMDI5N2QwYjZlN2I2YTViNjM3NzcxMTFhYzI5NDkzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SINmwqTKhROvoKsakVDAFQLbJxa46V6cCBOUrvbU5a0) 请考虑docker 等其他外部源的问题
> 
> ### 详细的执行日志
> 无

https://download.docker.com/linux/centos/7/x86_64/stable/repodata/repomd.xml

这不是你自己IPv6网络问题么？Docker CE官方源也是你自己选的
