### ISSUE TITLE
你好，加个docker-compose吧

### ISSUE THREAD

**Issue by A1me7n** [SuperManito/LinuxMirrors#57]
## 安装 Docker Compose
function install_docker_compose() {
    if [[ "${INSTALL_DOCKER_COMPOSE}" == "true" ]]; then
        echo -e "\n$WORKING 正在安装最新版本的 Docker Compose...\n"
        local latest_version=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d '"' -f 4)
        curl -L "https://github.com/docker/compose/releases/download/v${latest_version}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        echo -e "\n$COMPLETE Docker Compose 安装完成，版本：${latest_version}"
    fi
}

**Comment by SuperManito** [comment]
这不是我之前写的么。。。现在 Docker Compose V2 集成在了 Docker Cli 中，已经随脚本安装了，你的信息有些落后
