### ISSUE TITLE
可否提供对 Zorin OS 提供换源支持

### ISSUE THREAD

**Issue by hczs** [SuperManito/LinuxMirrors#58]
### 请在下方描述您的功能请求或建议

Zorin OS: https://zorin.com/os/
命令运行结果：
root@cheng-pc:~# bash <(curl -sSL https://linuxmirrors.cn/main.sh)

[错误] 当前系统版本不在本脚本的支持范围内，请前往官网查看支持列表！

**Comment by SuperManito** [comment]
> ### 请在下方描述您的功能请求或建议
> Zorin OS: https://zorin.com/os/ 命令运行结果： root@cheng-pc:~# bash <(curl -sSL https://linuxmirrors.cn/main.sh)
> 
> [错误] 当前系统版本不在本脚本的支持范围内，请前往官网查看支持列表！

已添加适配
