### ISSUE TITLE
ARM换源安装报错

### ISSUE THREAD

**Issue by zzvip888** [SuperManito/LinuxMirrors#59]
### 操作系统

CentOS / CentOS Stream

### 处理器架构

arm64 / arm/v8 / arm/v7 / arm/v6

### 系统详细信息

NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### 环境信息

Linux localhost.localdomain 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

### 描述您的问题

切换源后安装报
The GPG keys listed for the "CentOS-7.9.2009 - Updates" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.
 Failing package is: unzip-6.0-24.el7_9.aarch64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

--------------
网上查的解决方案都试了解决不了
手动切换了阿里的arm源
curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-altarch-7.repo
目前可以使用了

### 详细的执行日志

![image](https://github.com/user-attachments/assets/058af4b4-3069-4fba-8eca-41a29df1d497)

**Comment by SuperManito** [comment]
> ### 操作系统
> CentOS / CentOS Stream
> 
> ### 处理器架构
> arm64 / arm/v8 / arm/v7 / arm/v6
> 
> ### 系统详细信息
> NAME="CentOS Linux" VERSION="7 (AltArch)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (AltArch)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"
> 
> ### 环境信息
> Linux localhost.localdomain 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
> 
> ### 描述您的问题
> 切换源后安装报 The GPG keys listed for the "CentOS-7.9.2009 - Updates" repository are already installed but they are not correct for this package. Check that the correct key URLs are configured for this repository. Failing package is: unzip-6.0-24.el7_9.aarch64 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
> 
> 网上查的解决方案都试了解决不了 手动切换了阿里的arm源 curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-altarch-7.repo 目前可以使用了
> 
> ### 详细的执行日志
> ![image](https://private-user-images.githubusercontent.com/42537923/378302349-058af4b4-3069-4fba-8eca-41a29df1d497.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjkwNzMsIm5iZiI6MTcyOTUyODc3MywicGF0aCI6Ii80MjUzNzkyMy8zNzgzMDIzNDktMDU4YWY0YjQtMzA2OS00ZmJhLThlY2EtNDFhMjlkZjFkNDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2MzkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNWMzN2Y3NzI3NzM4YTgyMTYzNzY0NWQwMzcyZjE5ZTJhZTdlZDBkMTExZmRhNTgwZTJjNTBhODdkOTFkZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZzgeMxkVL0vtHWuVHKqyUv3cDHtgzJ2UJnu-5m3L_oU)

你系统里的 `/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7` 这个文件被你删了？
