### ISSUE TITLE
脚本报错 api查询请求失败

### ISSUE THREAD

**Issue by musouking** [SuperManito/LinuxMirrors#6]
## 1. 处理器架构

- [x] `x86_64` `x86_32`
- [ ] `arm64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 2. 使用环境

- [ ] `Debian`
- [ ] `Ubuntu`
- [ ] `Kali Linux`
- [ ] `Red Hat Enterprise Linux`
- [ ] `CentOS`
- [ ] `Fedora`

## 3. 使用环境版本

A：Linux OpenWrt 5.4.145 #0 SMP Fri Sep 17 17:45:36 2021 x86_64 GNU/Linux
![image](https://user-images.githubusercontent.com/17735261/133931488-193a8e79-e061-4d79-b955-31cd33584b82.png)

### (1) 具体问题
A：不好意思打扰大佬了，去gitee和dockerhub都没找到提issue的地方，就在大佬的项目下面冒昧提问了，如果不合适我自删
使用环境：笔记本装openwrt当主路由
问题如图12，在不开代理裸连的情况下所有脚本都报错网络问题
我以为是443端口被封了然而电脑没问题（图3）
想不通为什么连国内域名api.m.jd.com都能连不上
目前解决方法：给172.17.0.2开全局代理可以全部正常运行
安装的时候其实也有问题，ssh22端口连不上，cdn.npm.taobao.org也连不上...后来开全局代理解决。
望大佬不吝解惑，感谢

### (2) 详细的系统日志

A：
![image](https://user-images.githubusercontent.com/17735261/133930654-b87e1f35-f043-4b23-a8cb-842096ec3b5e.png)
![image](https://user-images.githubusercontent.com/17735261/133931059-31f36122-d50e-4781-bf49-2737db60cdc3.png)
![image](https://user-images.githubusercontent.com/17735261/133931083-f0c4adf7-5dd2-4a82-b59f-9b6f20fa90ef.png)

**Comment by musouking** [comment]
已解决
https://github.com/coolsnowwolf/lede/issues/1760#issuecomment-542985373

**Comment by SuperManito** [comment]
😀
