### ISSUE TITLE
OpenCloudOS 9 安装 Docker 失败

### ISSUE THREAD

**Issue by devhaozi** [SuperManito/LinuxMirrors#60]
### 操作系统

OpenCloudOS

### 处理器架构

x86_64 / x86_32

### 系统详细信息

```
NAME="OpenCloudOS"
VERSION="9.2"
ID="opencloudos"
ID_LIKE="opencloudos"
VERSION_ID="9.2"
PLATFORM_ID="platform:oc9"
PRETTY_NAME="OpenCloudOS 9.2"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:opencloudos:opencloudos:9"
HOME_URL="https://www.opencloudos.org/"
BUG_REPORT_URL="https://bugs.opencloudos.tech/"
```

### 环境信息

Linux VM-24-7-opencloudos 6.6.34-9.oc9.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 19 19:35:45 CST 2024 x86_64 GNU/Linux

### 描述您的问题

运行以下命令尝试安装 Docker 失败：

```
wget -T 20 -t 3 -O install-docker.sh https://linuxmirrors.cn/docker.sh
export CLOSE_FIREWALL="false"
bash install-docker.sh --source mirrors.tencent.com/docker-ce --source-registry docker.1ms.run --install-latested true --ignore-backup-tips
```

### 详细的执行日志

```
 +-----------------------------------+
 | ⡇  ⠄ ⣀⡀ ⡀⢀ ⡀⢀ ⡷⢾ ⠄ ⡀⣀ ⡀⣀ ⢀⡀ ⡀⣀ ⢀⣀ |
 | ⠧⠤ ⠇ ⠇⠸ ⠣⠼ ⠜⠣ ⠇⠸ ⠇ ⠏  ⠏  ⠣⠜ ⠏  ⠭⠕ |
 +-----------------------------------+
 欢迎使用 Docker Engine 安装与换源脚本

 运行环境 OpenCloudOS 9.2 x86_64
 系统时间 2024-11-03 02:39:08 Asia/Shanghai

[ >_ ] 开始生成软件源缓存...

BaseOS 9 - x86_64                                                                                                            1.3 MB/s | 1.1 MB     00:00    
AppStream 9 - x86_64                                                                                                         5.2 MB/s | 9.3 MB     00:01    
extras 9 - x86_64                                                                                                             46 kB/s | 8.3 kB     00:00    
Extra Packages for OpenCloudOS 9 - EPOL                                                                                       15 MB/s |  22 MB     00:01    
Metadata cache created.

[完成] 生成软件源缓存结束

Last metadata expiration check: 0:00:06 ago on Sun 03 Nov 2024 02:39:14 AM CST.
Package dnf-utils-4.3.1-1.oc9.2.noarch is already installed.
Package device-mapper-persistent-data-1.0.4-5.oc9.x86_64 is already installed.
Package lvm2-2.03.21-5.oc9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Adding repo from: https://mirrors.tencent.com/docker-ce/linux/centos/docker-ce.repo
BaseOS 9 - x86_64                                                                                                             42 kB/s | 3.8 kB     00:00    
AppStream 9 - x86_64                                                                                                          48 kB/s | 3.8 kB     00:00    
extras 9 - x86_64                                                                                                             45 kB/s | 3.7 kB     00:00    
Docker CE Stable - x86_64                                                                                                    201 kB/s |  58 kB     00:00    
Extra Packages for OpenCloudOS 9 - EPOL                                                                                       13 kB/s | 3.0 kB     00:00    
Metadata cache created.
No match for argument: docker
No match for argument: docker-client
No match for argument: docker-client-latest
No match for argument: docker-common
No match for argument: docker-latest
No match for argument: docker-latest-logrotate
No match for argument: docker-logrotate
No match for argument: docker-engine
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:00:04 ago on Sun 03 Nov 2024 02:39:22 AM CST.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides container-selinux >= 2:2.74 needed by docker-ce-3:27.3.1-1.el9.x86_64 from docker-ce-stable
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

[错误] 安装失败


     ------ 脚本执行结束 ------
 ┌───────────────────────────────┐
 │▞▀▖            ▙▗▌      ▗▐     │
 │▚▄ ▌ ▌▛▀▖▞▀▖▙▀▖▌▘▌▝▀▖▛▀▖▄▜▀ ▞▀▖│
 │▖ ▌▌ ▌▙▄▘▛▀ ▌  ▌ ▌▞▀▌▌ ▌▐▐ ▖▌ ▌│
 │▝▀ ▝▀▘▌  ▝▀▘▘  ▘ ▘▝▀▘▘ ▘▀▘▀ ▝▀ │
 └───────────────────────────────┘
     Powered by linuxmirrors.cn

```

**Comment by SuperManito** [comment]
> ### 操作系统
> OpenCloudOS
> 
> ### 处理器架构
> x86_64 / x86_32
> 
> ### 系统详细信息
> ```
> NAME="OpenCloudOS"
> VERSION="9.2"
> ID="opencloudos"
> ID_LIKE="opencloudos"
> VERSION_ID="9.2"
> PLATFORM_ID="platform:oc9"
> PRETTY_NAME="OpenCloudOS 9.2"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:opencloudos:opencloudos:9"
> HOME_URL="https://www.opencloudos.org/"
> BUG_REPORT_URL="https://bugs.opencloudos.tech/"
> ```
> 
> ### 环境信息
> Linux VM-24-7-opencloudos 6.6.34-9.oc9.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 19 19:35:45 CST 2024 x86_64 GNU/Linux
> 
> ### 描述您的问题
> 运行以下命令尝试安装 Docker 失败：
> 
> ```
> wget -T 20 -t 3 -O install-docker.sh https://linuxmirrors.cn/docker.sh
> export CLOSE_FIREWALL="false"
> bash install-docker.sh --source mirrors.tencent.com/docker-ce --source-registry docker.1ms.run --install-latested true --ignore-backup-tips
> ```
> 
> ### 详细的执行日志
> ```
>  +-----------------------------------+
>  | ⡇  ⠄ ⣀⡀ ⡀⢀ ⡀⢀ ⡷⢾ ⠄ ⡀⣀ ⡀⣀ ⢀⡀ ⡀⣀ ⢀⣀ |
>  | ⠧⠤ ⠇ ⠇⠸ ⠣⠼ ⠜⠣ ⠇⠸ ⠇ ⠏  ⠏  ⠣⠜ ⠏  ⠭⠕ |
>  +-----------------------------------+
>  欢迎使用 Docker Engine 安装与换源脚本
> 
>  运行环境 OpenCloudOS 9.2 x86_64
>  系统时间 2024-11-03 02:39:08 Asia/Shanghai
> 
> [ >_ ] 开始生成软件源缓存...
> 
> BaseOS 9 - x86_64                                                                                                            1.3 MB/s | 1.1 MB     00:00    
> AppStream 9 - x86_64                                                                                                         5.2 MB/s | 9.3 MB     00:01    
> extras 9 - x86_64                                                                                                             46 kB/s | 8.3 kB     00:00    
> Extra Packages for OpenCloudOS 9 - EPOL                                                                                       15 MB/s |  22 MB     00:01    
> Metadata cache created.
> 
> [完成] 生成软件源缓存结束
> 
> Last metadata expiration check: 0:00:06 ago on Sun 03 Nov 2024 02:39:14 AM CST.
> Package dnf-utils-4.3.1-1.oc9.2.noarch is already installed.
> Package device-mapper-persistent-data-1.0.4-5.oc9.x86_64 is already installed.
> Package lvm2-2.03.21-5.oc9.x86_64 is already installed.
> Dependencies resolved.
> Nothing to do.
> Complete!
> Adding repo from: https://mirrors.tencent.com/docker-ce/linux/centos/docker-ce.repo
> BaseOS 9 - x86_64                                                                                                             42 kB/s | 3.8 kB     00:00    
> AppStream 9 - x86_64                                                                                                          48 kB/s | 3.8 kB     00:00    
> extras 9 - x86_64                                                                                                             45 kB/s | 3.7 kB     00:00    
> Docker CE Stable - x86_64                                                                                                    201 kB/s |  58 kB     00:00    
> Extra Packages for OpenCloudOS 9 - EPOL                                                                                       13 kB/s | 3.0 kB     00:00    
> Metadata cache created.
> No match for argument: docker
> No match for argument: docker-client
> No match for argument: docker-client-latest
> No match for argument: docker-common
> No match for argument: docker-latest
> No match for argument: docker-latest-logrotate
> No match for argument: docker-logrotate
> No match for argument: docker-engine
> No packages marked for removal.
> Dependencies resolved.
> Nothing to do.
> Complete!
> Last metadata expiration check: 0:00:04 ago on Sun 03 Nov 2024 02:39:22 AM CST.
> Error: 
>  Problem: cannot install the best candidate for the job
>   - nothing provides container-selinux >= 2:2.74 needed by docker-ce-3:27.3.1-1.el9.x86_64 from docker-ce-stable
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> 
> [错误] 安装失败
> 
> 
>      ------ 脚本执行结束 ------
>  ┌───────────────────────────────┐
>  │▞▀▖            ▙▗▌      ▗▐     │
>  │▚▄ ▌ ▌▛▀▖▞▀▖▙▀▖▌▘▌▝▀▖▛▀▖▄▜▀ ▞▀▖│
>  │▖ ▌▌ ▌▙▄▘▛▀ ▌  ▌ ▌▞▀▌▌ ▌▐▐ ▖▌ ▌│
>  │▝▀ ▝▀▘▌  ▝▀▘▘  ▘ ▘▝▀▘▘ ▘▀▘▀ ▝▀ │
>  └───────────────────────────────┘
>      Powered by linuxmirrors.cn
> ```

应该是 OpenCloudOS 官方的问题

我好像成功测试过 OpenCloudOS Stream 23 但不记得有没有测试过 OpenCloudOS 9，毕竟 9 版本已脱离红帽出现问题是预料之内的，Anolis OS 和 openEuler 一样装的好好的，看来要停止支持 OpenCloudOS 9 了

另外给你个安装参考命令
```bash
dnf install -y docker
systemctl enable --now docker
```
