### ISSUE TITLE
Change Mirror中南非NTT(Dimension Data)镜像地址不正确

### ISSUE THREAD

**Issue by dzvision** [SuperManito/LinuxMirrors#61]
### 操作系统

Rocky Linux

### 处理器架构

x86_64 / x86_32

### 系统详细信息

NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"

### 环境信息

Linux iZrj9afdyyuz2pu3kt56gmZ 5.14.0-427.18.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 27 16:35:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### 描述您的问题

Change Mirror中南非NTT(Dimension Data)镜像地址不正确，我认真看了一下，发现不太会改，所以就没有pull。
以Rocky Linux为例，他的镜像站有两个，一个是[rocky](https://rocky.dimensiondata.com/);另一个就是[Mirror](https://mirror.dimensiondata.com/mirror/rockylinux.org/)。

目前的语法会导致地址为：https://mirror.dimensiondata.com/rocky/$releasever/..... (也就是错误的地址)
同时该镜像站并无EPEL镜像。

### 详细的执行日志

Rocky Linux 9 - BaseOS                          103  B/s | 196  B     00:01
Errors during downloading metadata for repository 'baseos':
  - Status code: 404 for https://mirror.dimensiondata.com/rocky/9/BaseOS/x86_64/os/repodata/repomd.xml (IP: x)
Error: Failed to download metadata for repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

[ >_ ] 开始生成软件源缓存...

Extra Packages for Enterprise Linux 9 - x86_64  107  B/s | 196  B     00:01
Errors during downloading metadata for repository 'epel':
  - Status code: 404 for https://mirror.dimensiondata.com/epel/9/Everything/x86_64/repodata/repomd.xml (IP: x)
Error: Failed to download metadata for repo 'epel': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

[失败] 软件源更换完毕，但生成软件源缓存失败

请再次执行脚本并更换相同软件源后进行尝试，若仍然生成软件源缓存失败那么可能由以下原因导致：

1. 网络连通性问题：例如连接异常、由地区影响的网络间歇式中断、禁止外部访问等

2. 目标软件源异常：请手动前往软件源（镜像站）地址进行验证：https://mirror.dimensiondata.com/rocky

      若报错内容是提示某个文件不存在那么有可能是软件源的问题，多常见于正在同步中的软件源
      若报错内容是目录（path）不存在也有可能是目标软件源不存在当前系统镜像仓库，即不支持当前系统
      建议更换其它镜像站进行尝试，少数情况下软件源若处于同步中状态则可能会出现文件同步错误问题

3. 原有软件源报错：请先排除系统原有的其它软件源报错，因为脚本不会干预这些无关的软件源仓库，解决后重新运行脚本即可

**Comment by SuperManito** [comment]
![image](https://github.com/user-attachments/assets/b44f396d-c4e1-46d5-8bce-0a24c93c163d)
