### ISSUE TITLE
kali 下使用 ”Docker 安装脚本”， 换源不生效

### ISSUE THREAD

**Issue by gandli** [SuperManito/LinuxMirrors#62]
### 操作系统

Kali Linux

### 处理器架构

x86_64 / x86_32

### 系统详细信息

```
┌──(kali㉿kali)-[~]
└─$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.3"
VERSION="2024.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

### 环境信息

Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux

### 描述您的问题

使用`bash <(curl -sSL https://linuxmirrors.cn/docker.sh)`安装docker后，换源未达到预期。
```
……
Processing triggers for libc-bin (2.38-13) ...
Processing triggers for man-db (2.12.1-2) ...
Processing triggers for kali-menu (2024.3.1) ...

当前安装版本：Docker version 27.3.1, build ce12230

[完成] 安装完成

---------- 脚本执行结束 ----------

Powered by https://linuxmirrors.cn

                                                                                                                                                             
┌──(root㉿kali)-[~]
└─# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
                                                                                                                                                             
┌──(root㉿kali)-[~]
└─# docker run --rm hello-docker 
Unable to find image 'hello-docker:latest' locally
docker: Error response from daemon: pull access denied for hello-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

### 详细的执行日志

![image](https://github.com/user-attachments/assets/1f785e3f-b245-4c03-b43b-04e0b65218a3)

**Comment by SuperManito** [comment]
> ### 操作系统
> Kali Linux
> 
> ### 处理器架构
> x86_64 / x86_32
> 
> ### 系统详细信息
> ```
> ┌──(kali㉿kali)-[~]
> └─$ cat /etc/os-release
> PRETTY_NAME="Kali GNU/Linux Rolling"
> NAME="Kali GNU/Linux"
> VERSION_ID="2024.3"
> VERSION="2024.3"
> VERSION_CODENAME=kali-rolling
> ID=kali
> ID_LIKE=debian
> HOME_URL="https://www.kali.org/"
> SUPPORT_URL="https://forums.kali.org/"
> BUG_REPORT_URL="https://bugs.kali.org/"
> ANSI_COLOR="1;31"
> ```
> 
> ### 环境信息
> Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux
> 
> ### 描述您的问题
> 使用`bash <(curl -sSL https://linuxmirrors.cn/docker.sh)`安装docker后，换源未达到预期。
> 
> ```
> ……
> Processing triggers for libc-bin (2.38-13) ...
> Processing triggers for man-db (2.12.1-2) ...
> Processing triggers for kali-menu (2024.3.1) ...
> 
> 当前安装版本：Docker version 27.3.1, build ce12230
> 
> [完成] 安装完成
> 
> ---------- 脚本执行结束 ----------
> 
> Powered by https://linuxmirrors.cn
> 
>                                                                                                                                                              
> ┌──(root㉿kali)-[~]
> └─# docker ps
> CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
>                                                                                                                                                              
> ┌──(root㉿kali)-[~]
> └─# docker run --rm hello-docker 
> Unable to find image 'hello-docker:latest' locally
> docker: Error response from daemon: pull access denied for hello-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.
> ```
> 
> ### 详细的执行日志
> ![image](https://private-user-images.githubusercontent.com/85359251/386512267-1f785e3f-b245-4c03-b43b-04e0b65218a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTkyNDksIm5iZiI6MTczMTY1ODk0OSwicGF0aCI6Ii84NTM1OTI1MS8zODY1MTIyNjctMWY3ODVlM2YtYjI0NS00YzAzLWI0M2ItMDRlMGI2NTIxOGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA4MjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNzU5NWVhNzgxMGMwYzkxNmUwMzQ1NDkxMzhhZDExOWExZDA3ZjQ0MzhhODkzNjNkYmFjYjk4NmUzY2Q5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YwhmZu9HbpHUi-2mtn3m6kf-gsb9-W7xbpzAKzx6Sxg)

你自己翻译一下docker返回的报错好吧，你的英文水平有待提高
