### ISSUE TITLE
系统软件源增加建议

### ISSUE THREAD

**Issue by sky22333** [SuperManito/LinuxMirrors#64]
### 请在下方描述您的功能请求或建议

感谢作者维护脚本为我们提供了便利。希望能增加一下各个系统的官方软件源，例如`debian`，`ubuntu`等等对应版本的官方软件源，因为有很多小`IDC`商家或者便宜的海外机器内置的不知道是哪里的源，很多包都没有，所以需要换回官方源，个人用户用这些便宜的海外机器还是很多的，换源需求很大。

**Comment by SuperManito** [comment]
> ### 请在下方描述您的功能请求或建议
> 
> 感谢作者维护脚本为我们提供了便利。希望能增加一下各个系统的官方软件源，例如`debian`，`ubuntu`等等对应版本的官方软件源，因为有很多小`IDC`商家或者便宜的海外机器内置的不知道是哪里的源，很多包都没有，所以需要换回官方源，个人用户用这些便宜的海外机器还是很多的，换源需求很大。

认真看文档
