### ISSUE TITLE
OpenEuler 24.03 LTS 无法正常更换镜像

### ISSUE THREAD

**Issue by AkarinLiu** [SuperManito/LinuxMirrors#66]
### 操作系统

openEuler

### 处理器架构

x86_64 / x86_32

### 系统详细信息

```
NAME="openEuler"
VERSION="24.03 (LTS)"
ID="openEuler"
VERSION_ID="24.03"
PRETTY_NAME="openEuler 24.03 (LTS)"
ANSI_COLOR="0;31"
```

### 环境信息

Linux DESKTOP-L38U9DP 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### 描述您的问题

执行该脚本后，导致 dnf update 失效

### 详细的执行日志

```
+-----------------------------------+
| ⡇  ⠄ ⣀⡀ ⡀⢀ ⡀⢀ ⡷⢾ ⠄ ⡀⣀ ⡀⣀ ⢀⡀ ⡀⣀ ⢀⣀ |
| ⠧⠤ ⠇ ⠇⠸ ⠣⠼ ⠜⠣ ⠇⠸ ⠇ ⠏  ⠏  ⠣⠜ ⠏  ⠭⠕ |
+-----------------------------------+
欢迎使用 GNU/Linux 更换系统软件源脚本

运行环境 openEuler 24.03 (LTS) x86_64
系统时间 2024-12-27 13:49 Asia/Shanghai

➜  火山引擎

╭─ 默认使用软件源的公网地址，是否继续?
│
╰─ ● 是 / ○ 否
^[[A
╭─ 检测到系统存在已备份的 repo 源文件，是否跳过覆盖备份?
│
╰─ ○ 是 / ● 否

'/etc/yum.repos.d/openEuler.repo' -> '/etc/yum.repos.d.bak/openEuler.repo'
'/etc/yum.repos.d/yum.repos.d.bak' -> '/etc/yum.repos.d.bak/yum.repos.d.bak'
'/etc/yum.repos.d/yum.repos.d.bak/openEuler.repo' -> '/etc/yum.repos.d.bak/yum.repos.d.bak/openEuler.repo'
/dev/fd/63: line 2098: gen_repo_files_openEuler: command not found
sed: can't read openEuler.repo: No such file or directory

>_ 开始生成软件源缓存...

There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".

✔ 软件源更换完毕

╭─ 是否跳过更新软件包?
│
╰─ ● 是 / ○ 否

✨️ Powered by https://linuxmirrors.cn
```

**Comment by SuperManito** [comment]
> ### 操作系统
> openEuler
> 
> ### 处理器架构
> x86_64 / x86_32
> 
> ### 系统详细信息
> ```
> NAME="openEuler"
> VERSION="24.03 (LTS)"
> ID="openEuler"
> VERSION_ID="24.03"
> PRETTY_NAME="openEuler 24.03 (LTS)"
> ANSI_COLOR="0;31"
> ```
> 
> ### 环境信息
> Linux DESKTOP-L38U9DP 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> 
> ### 描述您的问题
> 执行该脚本后，导致 dnf update 失效
> 
> ### 详细的执行日志
> ```
> +-----------------------------------+
> | ⡇  ⠄ ⣀⡀ ⡀⢀ ⡀⢀ ⡷⢾ ⠄ ⡀⣀ ⡀⣀ ⢀⡀ ⡀⣀ ⢀⣀ |
> | ⠧⠤ ⠇ ⠇⠸ ⠣⠼ ⠜⠣ ⠇⠸ ⠇ ⠏  ⠏  ⠣⠜ ⠏  ⠭⠕ |
> +-----------------------------------+
> 欢迎使用 GNU/Linux 更换系统软件源脚本
> 
> 运行环境 openEuler 24.03 (LTS) x86_64
> 系统时间 2024-12-27 13:49 Asia/Shanghai
> 
> ➜  火山引擎
> 
> ╭─ 默认使用软件源的公网地址，是否继续?
> │
> ╰─ ● 是 / ○ 否
> ^[[A
> ╭─ 检测到系统存在已备份的 repo 源文件，是否跳过覆盖备份?
> │
> ╰─ ○ 是 / ● 否
> 
> '/etc/yum.repos.d/openEuler.repo' -> '/etc/yum.repos.d.bak/openEuler.repo'
> '/etc/yum.repos.d/yum.repos.d.bak' -> '/etc/yum.repos.d.bak/yum.repos.d.bak'
> '/etc/yum.repos.d/yum.repos.d.bak/openEuler.repo' -> '/etc/yum.repos.d.bak/yum.repos.d.bak/openEuler.repo'
> /dev/fd/63: line 2098: gen_repo_files_openEuler: command not found
> sed: can't read openEuler.repo: No such file or directory
> 
> >_ 开始生成软件源缓存...
> 
> There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
> 
> ✔ 软件源更换完毕
> 
> ╭─ 是否跳过更新软件包?
> │
> ╰─ ● 是 / ○ 否
> 
> ✨️ Powered by https://linuxmirrors.cn
> ```

Bug 已修
