### ISSUE TITLE
运行步骤

### ISSUE THREAD

**Issue by 151110151** [SuperManito/LinuxMirrors#8]
bash <(curl -sSL https://gitee.com/SuperManito/LinuxMirrors/raw/main/ChangeMirrors.sh)  运行这个后，怎么操作(安装成功了)

**Comment by SuperManito** [comment]
请详细描述你的问题???

**Comment by 151110151** [comment]
我想按着您的教程操作，我现在执行了这个命令(bash <(curl -sSL https://gitee.com/SuperManito/LinuxMirrors/raw/main/ChangeMirrors.sh))，接下来我该怎么操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperManito/LinuxMirrors"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperManito/LinuxMirrors] 运行步骤 (Issue #8)





 
请详细描述你的问题???
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SuperManito** [comment]
交互...
