### ISSUE TITLE
在Oracle Linux上安装软件报错

### ISSUE THREAD

**Issue by GuanTu** [SuperManito/LinuxMirrors#9]
## 1. 处理器架构

- [x] `x86_64` `x86_32`
- [ ] `arm64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 2. 使用环境

- [ ] `Debian`
- [ ] `Ubuntu`
- [ ] `Kali Linux`
- [ ] `Red Hat Enterprise Linux`
- [ ] `CentOS`
- [ ] `Fedora`
- [x] `Oracle Linux`

## 3. 使用环境版本

A：Linux localhost.localdomain 4.14.35-1818.3.3.el7uek.x86_64 #2 SMP Mon Sep 24 14:45:01 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

### (1) 具体问题
A：在Oracle Linux上执行脚本选择阿里云后，yum安装软件报错

### (2) 详细的系统日志

A：
```
[root@localhost ~]# yum install -y ntpdate net-tools telnet
Loaded plugins: ulninfo
Resolving Dependencies
--> Running transaction check
---> Package net-tools.x86_64 0:2.0-0.25.20131004git.el7 will be installed
---> Package ntpdate.x86_64 0:4.2.6p5-29.el7.centos.2 will be installed
---> Package telnet.x86_64 1:0.17-66.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================
 Package                     Arch                     Version                                      Repository                 Size
===================================================================================================================================
Installing:
 net-tools                   x86_64                   2.0-0.25.20131004git.el7                     base                      306 k
 ntpdate                     x86_64                   4.2.6p5-29.el7.centos.2                      base                       87 k
 telnet                      x86_64                   1:0.17-66.el7                                updates                    64 k

Transaction Summary
===================================================================================================================================
Install  3 Packages

Total download size: 457 k
Installed size: 1.1 M
Downloading packages:
warning: /var/cache/yum/x86_64/7Server/updates/packages/telnet-0.17-66.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for telnet-0.17-66.el7.x86_64.rpm is not installed
(1/3): telnet-0.17-66.el7.x86_64.rpm                                                                        |  64 kB  00:00:00     
Public key for ntpdate-4.2.6p5-29.el7.centos.2.x86_64.rpm is not installed                       ]  0.0 B/s | 147 kB  --:--:-- ETA 
(2/3): ntpdate-4.2.6p5-29.el7.centos.2.x86_64.rpm                                                           |  87 kB  00:00:00     
(3/3): net-tools-2.0-0.25.20131004git.el7.x86_64.rpm                                                        | 306 kB  00:00:01     
-----------------------------------------------------------------------------------------------------------------------------------
Total                                                                                              297 kB/s | 457 kB  00:00:01     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7


GPG key retrieval failed: [Errno 14] curl#37 - "Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"

```

**Comment by GuanTu** [comment]
运行环境  Oracle Linux Server 7.6 x86_64

**Comment by SuperManito** [comment]
> ## 1. 处理器架构
> * [x]  `x86_64` `x86_32`
> * [ ]  `arm64` `arm/v8` `arm/v7` `arm/v6`
> * [ ]  `ppc64le` `s390x`
> * [ ]  `Other`
> 
> ## 2. 使用环境
> * [ ]  `Debian`
> * [ ]  `Ubuntu`
> * [ ]  `Kali Linux`
> * [ ]  `Red Hat Enterprise Linux`
> * [ ]  `CentOS`
> * [ ]  `Fedora`
> * [x]  `Oracle Linux`
> 
> ## 3. 使用环境版本
> A：Linux localhost.localdomain 4.14.35-1818.3.3.el7uek.x86_64 #2 SMP Mon Sep 24 14:45:01 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
> 
> ## 4. 详细叙述您的问题
> ### (1) 具体问题
> A：在Oracle Linux上执行脚本选择阿里云后，yum安装软件报错
> 
> ### (2) 详细的系统日志
> A：
> 
> ```
> [root@localhost ~]# yum install -y ntpdate net-tools telnet
> Loaded plugins: ulninfo
> Resolving Dependencies
> --> Running transaction check
> ---> Package net-tools.x86_64 0:2.0-0.25.20131004git.el7 will be installed
> ---> Package ntpdate.x86_64 0:4.2.6p5-29.el7.centos.2 will be installed
> ---> Package telnet.x86_64 1:0.17-66.el7 will be installed
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> ===================================================================================================================================
>  Package                     Arch                     Version                                      Repository                 Size
> ===================================================================================================================================
> Installing:
>  net-tools                   x86_64                   2.0-0.25.20131004git.el7                     base                      306 k
>  ntpdate                     x86_64                   4.2.6p5-29.el7.centos.2                      base                       87 k
>  telnet                      x86_64                   1:0.17-66.el7                                updates                    64 k
> 
> Transaction Summary
> ===================================================================================================================================
> Install  3 Packages
> 
> Total download size: 457 k
> Installed size: 1.1 M
> Downloading packages:
> warning: /var/cache/yum/x86_64/7Server/updates/packages/telnet-0.17-66.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
> Public key for telnet-0.17-66.el7.x86_64.rpm is not installed
> (1/3): telnet-0.17-66.el7.x86_64.rpm                                                                        |  64 kB  00:00:00     
> Public key for ntpdate-4.2.6p5-29.el7.centos.2.x86_64.rpm is not installed                       ]  0.0 B/s | 147 kB  --:--:-- ETA 
> (2/3): ntpdate-4.2.6p5-29.el7.centos.2.x86_64.rpm                                                           |  87 kB  00:00:00     
> (3/3): net-tools-2.0-0.25.20131004git.el7.x86_64.rpm                                                        | 306 kB  00:00:01     
> -----------------------------------------------------------------------------------------------------------------------------------
> Total                                                                                              297 kB/s | 457 kB  00:00:01     
> Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
> 
> 
> GPG key retrieval failed: [Errno 14] curl#37 - "Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"
> ```

- 试下命令

```bash
cd /etc/pki/rpm-gpg
wget https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
```

**Comment by GuanTu** [comment]
我从另外一台CentOS7服务器拷贝`/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7` 到Oracle Linux就可以了

**Comment by GuanTu** [comment]
> > ## 1. 处理器架构
> > 
> > * [x]   `x86_64` `x86_32`
> > * [ ]   `arm64` `arm/v8` `arm/v7` `arm/v6`
> > * [ ]   `ppc64le` `s390x`
> > * [ ]   `Other`
> > 
> > ## 2. 使用环境
> > 
> > * [ ]   `Debian`
> > * [ ]   `Ubuntu`
> > * [ ]   `Kali Linux`
> > * [ ]   `Red Hat Enterprise Linux`
> > * [ ]   `CentOS`
> > * [ ]   `Fedora`
> > * [x]   `Oracle Linux`
> > 
> > ## 3. 使用环境版本
> > A：Linux localhost.localdomain 4.14.35-1818.3.3.el7uek.x86_64 #2 SMP Mon Sep 24 14:45:01 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
> > ## 4. 详细叙述您的问题
> > ### (1) 具体问题
> > A：在Oracle Linux上执行脚本选择阿里云后，yum安装软件报错
> > ### (2) 详细的系统日志
> > A：
> > ```
> > [root@localhost ~]# yum install -y ntpdate net-tools telnet
> > Loaded plugins: ulninfo
> > Resolving Dependencies
> > --> Running transaction check
> > ---> Package net-tools.x86_64 0:2.0-0.25.20131004git.el7 will be installed
> > ---> Package ntpdate.x86_64 0:4.2.6p5-29.el7.centos.2 will be installed
> > ---> Package telnet.x86_64 1:0.17-66.el7 will be installed
> > --> Finished Dependency Resolution
> > 
> > Dependencies Resolved
> > 
> > ===================================================================================================================================
> >  Package                     Arch                     Version                                      Repository                 Size
> > ===================================================================================================================================
> > Installing:
> >  net-tools                   x86_64                   2.0-0.25.20131004git.el7                     base                      306 k
> >  ntpdate                     x86_64                   4.2.6p5-29.el7.centos.2                      base                       87 k
> >  telnet                      x86_64                   1:0.17-66.el7                                updates                    64 k
> > 
> > Transaction Summary
> > ===================================================================================================================================
> > Install  3 Packages
> > 
> > Total download size: 457 k
> > Installed size: 1.1 M
> > Downloading packages:
> > warning: /var/cache/yum/x86_64/7Server/updates/packages/telnet-0.17-66.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
> > Public key for telnet-0.17-66.el7.x86_64.rpm is not installed
> > (1/3): telnet-0.17-66.el7.x86_64.rpm                                                                        |  64 kB  00:00:00     
> > Public key for ntpdate-4.2.6p5-29.el7.centos.2.x86_64.rpm is not installed                       ]  0.0 B/s | 147 kB  --:--:-- ETA 
> > (2/3): ntpdate-4.2.6p5-29.el7.centos.2.x86_64.rpm                                                           |  87 kB  00:00:00     
> > (3/3): net-tools-2.0-0.25.20131004git.el7.x86_64.rpm                                                        | 306 kB  00:00:01     
> > -----------------------------------------------------------------------------------------------------------------------------------
> > Total                                                                                              297 kB/s | 457 kB  00:00:01     
> > Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
> > 
> > 
> > GPG key retrieval failed: [Errno 14] curl#37 - "Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"
> > ```
> 
> * 试下命令
> 
> ```shell
> cd /etc/pki/rpm-gpg
> wget https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
> ```

感谢回复

**Comment by SuperManito** [comment]
不客气，我在 `Oracle Linux 8` 上测试没有出现该问题，我无法判断在 `Oracle Linux 7` 上是否本应存在该文件，这种都是兼容性的小问题
